name: Generate Snake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:   
  push:
    branches:
      - main

jobs:
  build:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: <tên_user_của_bạn>
          outputs: dist/snake.svg

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
